---
dependency:
  name: galaxy
driver:
  name: gce
  #lint: |
    #yamllint
platforms:
  #  - name: instance-travis
  # zone: europe-west1-b
  # machine_type: f1-micro
  # image: ubuntu-1604-xenial-v20170919
  - name: instance
    instance_names: "{{ item.name }}"
    zone: "{{ item.zone }}"
    machine_type: "{{ item.machine_type }}"
    image: "{{ item.image }}"
    service_account_email: "{{ lookup('env', 'GCE_SERVICE_ACCOUNT_EMAIL') }}"
    credentials_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE') }}"
    project_id: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
provisioner:
  name: ansible
  lint: |
    ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
